//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppProiect.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logIn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsAppProiect.ServiceReference1.logInResponse logIn(WindowsFormsAppProiect.ServiceReference1.logInRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logIn", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.logInResponse> logInAsync(WindowsFormsAppProiect.ServiceReference1.logInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addUser(string username, string password, string email, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addUserAsync(string username, string password, string email, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/makeAdmin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool makeAdmin(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/makeAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> makeAdminAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addFaculty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool addFaculty(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addFaculty", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> addFacultyAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteFaculty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deleteFaculty(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteFaculty", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteFacultyAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateFaculty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool updateFaculty(string newName, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateFaculty", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> updateFacultyAsync(string newName, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addPost(string username, string title, string content, string course, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPost", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addPostAsync(string username, string title, string content, string course, string link);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editPost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editPost(string title, string content, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editPost", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editPostAsync(string title, string content, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePost", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeletePost(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePost", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeletePostAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postedBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string postedBy(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postedBy", ReplyAction="*")]
        System.Threading.Tasks.Task<string> postedByAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addCourse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addCourse(int year, int semester, string faculty, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addCourseAsync(int year, int semester, string faculty, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editCourseName(string newName, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseName", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editCourseNameAsync(string newName, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseYear", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editCourseYear(int newYear, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseYear", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editCourseYearAsync(int newYear, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseSemester", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editCourseSemester(int newSem, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseSemester", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editCourseSemesterAsync(int newSem, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseFaculty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editCourseFaculty(string newFaculty, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editCourseFaculty", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editCourseFacultyAsync(string newFaculty, string oldName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCourse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool deleteCourse(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> deleteCourseAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllPosts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAllPosts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllPosts", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllPostsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllFaculties", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAllFaculties();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllFaculties", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllFacultiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCourses", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAllCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCourses", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCourse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getCourse(string facultate, int an, int semestru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCourseAsync(string facultate, int an, int semestru);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool editName(string newName, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editName", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> editNameAsync(string newName, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editUsername", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editUsername(string newUsername, string oldUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editUsernameAsync(string newUsername, string oldUsername);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsernameById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getUsernameById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsernameById", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getUsernameByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editEmail(string newEmail, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editEmailAsync(string newEmail, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string editPassword(string newPassword, string oldPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<string> editPasswordAsync(string newPassword, string oldPassword, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getUserData(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUserData", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getUserDataAsync(string username);
        
        // CODEGEN: Parameter 'arr' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsAppProiect.ServiceReference1.insertImageResponse insertImage(WindowsFormsAppProiect.ServiceReference1.insertImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertImage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.insertImageResponse> insertImageAsync(WindowsFormsAppProiect.ServiceReference1.insertImageRequest request);
        
        // CODEGEN: Parameter 'getImageResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WindowsFormsAppProiect.ServiceReference1.getImageResponse getImage(WindowsFormsAppProiect.ServiceReference1.getImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getImage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.getImageResponse> getImageAsync(WindowsFormsAppProiect.ServiceReference1.getImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPostByTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPostByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPostByTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPostByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getComments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getComments(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getComments", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getCommentsAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postComment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void postComment(string title, int idUser, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postComment", ReplyAction="*")]
        System.Threading.Tasks.Task postCommentAsync(string title, int idUser, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLinkByTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getLinkByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLinkByTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getLinkByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPostById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getPostById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPostById", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getPostByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTitleByCourse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTitleByCourse(string course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTitleByCourse", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getTitleByCourseAsync(string course);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logIn", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class logInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int isAdmin;
        
        public logInRequest() {
        }
        
        public logInRequest(string username, string password, int id, int isAdmin) {
            this.username = username;
            this.password = password;
            this.id = id;
            this.isAdmin = isAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="logInResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class logInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int logInResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int isAdmin;
        
        public logInResponse() {
        }
        
        public logInResponse(int logInResult, int id, int isAdmin) {
            this.logInResult = logInResult;
            this.id = id;
            this.isAdmin = isAdmin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] arr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string username;
        
        public insertImageRequest() {
        }
        
        public insertImageRequest(byte[] arr, string username) {
            this.arr = arr;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class insertImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string insertImageResult;
        
        public insertImageResponse() {
        }
        
        public insertImageResponse(string insertImageResult) {
            this.insertImageResult = insertImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        public getImageRequest() {
        }
        
        public getImageRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getImageResult;
        
        public getImageResponse() {
        }
        
        public getImageResponse(byte[] getImageResult) {
            this.getImageResult = getImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsAppProiect.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsAppProiect.ServiceReference1.WebService1Soap>, WindowsFormsAppProiect.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppProiect.ServiceReference1.logInResponse WindowsFormsAppProiect.ServiceReference1.WebService1Soap.logIn(WindowsFormsAppProiect.ServiceReference1.logInRequest request) {
            return base.Channel.logIn(request);
        }
        
        public int logIn(string username, string password, ref int id, ref int isAdmin) {
            WindowsFormsAppProiect.ServiceReference1.logInRequest inValue = new WindowsFormsAppProiect.ServiceReference1.logInRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.id = id;
            inValue.isAdmin = isAdmin;
            WindowsFormsAppProiect.ServiceReference1.logInResponse retVal = ((WindowsFormsAppProiect.ServiceReference1.WebService1Soap)(this)).logIn(inValue);
            id = retVal.id;
            isAdmin = retVal.isAdmin;
            return retVal.logInResult;
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.logInResponse> logInAsync(WindowsFormsAppProiect.ServiceReference1.logInRequest request) {
            return base.Channel.logInAsync(request);
        }
        
        public string addUser(string username, string password, string email, string name) {
            return base.Channel.addUser(username, password, email, name);
        }
        
        public System.Threading.Tasks.Task<string> addUserAsync(string username, string password, string email, string name) {
            return base.Channel.addUserAsync(username, password, email, name);
        }
        
        public bool makeAdmin(string username) {
            return base.Channel.makeAdmin(username);
        }
        
        public System.Threading.Tasks.Task<bool> makeAdminAsync(string username) {
            return base.Channel.makeAdminAsync(username);
        }
        
        public bool addFaculty(string name) {
            return base.Channel.addFaculty(name);
        }
        
        public System.Threading.Tasks.Task<bool> addFacultyAsync(string name) {
            return base.Channel.addFacultyAsync(name);
        }
        
        public bool deleteFaculty(string name) {
            return base.Channel.deleteFaculty(name);
        }
        
        public System.Threading.Tasks.Task<bool> deleteFacultyAsync(string name) {
            return base.Channel.deleteFacultyAsync(name);
        }
        
        public bool updateFaculty(string newName, string oldName) {
            return base.Channel.updateFaculty(newName, oldName);
        }
        
        public System.Threading.Tasks.Task<bool> updateFacultyAsync(string newName, string oldName) {
            return base.Channel.updateFacultyAsync(newName, oldName);
        }
        
        public string addPost(string username, string title, string content, string course, string link) {
            return base.Channel.addPost(username, title, content, course, link);
        }
        
        public System.Threading.Tasks.Task<string> addPostAsync(string username, string title, string content, string course, string link) {
            return base.Channel.addPostAsync(username, title, content, course, link);
        }
        
        public string editPost(string title, string content, int id) {
            return base.Channel.editPost(title, content, id);
        }
        
        public System.Threading.Tasks.Task<string> editPostAsync(string title, string content, int id) {
            return base.Channel.editPostAsync(title, content, id);
        }
        
        public bool DeletePost(string title) {
            return base.Channel.DeletePost(title);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePostAsync(string title) {
            return base.Channel.DeletePostAsync(title);
        }
        
        public string postedBy(string title) {
            return base.Channel.postedBy(title);
        }
        
        public System.Threading.Tasks.Task<string> postedByAsync(string title) {
            return base.Channel.postedByAsync(title);
        }
        
        public string addCourse(int year, int semester, string faculty, string name) {
            return base.Channel.addCourse(year, semester, faculty, name);
        }
        
        public System.Threading.Tasks.Task<string> addCourseAsync(int year, int semester, string faculty, string name) {
            return base.Channel.addCourseAsync(year, semester, faculty, name);
        }
        
        public string editCourseName(string newName, string oldName) {
            return base.Channel.editCourseName(newName, oldName);
        }
        
        public System.Threading.Tasks.Task<string> editCourseNameAsync(string newName, string oldName) {
            return base.Channel.editCourseNameAsync(newName, oldName);
        }
        
        public string editCourseYear(int newYear, string oldName) {
            return base.Channel.editCourseYear(newYear, oldName);
        }
        
        public System.Threading.Tasks.Task<string> editCourseYearAsync(int newYear, string oldName) {
            return base.Channel.editCourseYearAsync(newYear, oldName);
        }
        
        public string editCourseSemester(int newSem, string oldName) {
            return base.Channel.editCourseSemester(newSem, oldName);
        }
        
        public System.Threading.Tasks.Task<string> editCourseSemesterAsync(int newSem, string oldName) {
            return base.Channel.editCourseSemesterAsync(newSem, oldName);
        }
        
        public string editCourseFaculty(string newFaculty, string oldName) {
            return base.Channel.editCourseFaculty(newFaculty, oldName);
        }
        
        public System.Threading.Tasks.Task<string> editCourseFacultyAsync(string newFaculty, string oldName) {
            return base.Channel.editCourseFacultyAsync(newFaculty, oldName);
        }
        
        public bool deleteCourse(string name) {
            return base.Channel.deleteCourse(name);
        }
        
        public System.Threading.Tasks.Task<bool> deleteCourseAsync(string name) {
            return base.Channel.deleteCourseAsync(name);
        }
        
        public System.Data.DataSet getAllPosts() {
            return base.Channel.getAllPosts();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllPostsAsync() {
            return base.Channel.getAllPostsAsync();
        }
        
        public System.Data.DataSet getAllFaculties() {
            return base.Channel.getAllFaculties();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllFacultiesAsync() {
            return base.Channel.getAllFacultiesAsync();
        }
        
        public System.Data.DataSet getAllCourses() {
            return base.Channel.getAllCourses();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllCoursesAsync() {
            return base.Channel.getAllCoursesAsync();
        }
        
        public System.Data.DataSet getCourse(string facultate, int an, int semestru) {
            return base.Channel.getCourse(facultate, an, semestru);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCourseAsync(string facultate, int an, int semestru) {
            return base.Channel.getCourseAsync(facultate, an, semestru);
        }
        
        public bool editName(string newName, string username) {
            return base.Channel.editName(newName, username);
        }
        
        public System.Threading.Tasks.Task<bool> editNameAsync(string newName, string username) {
            return base.Channel.editNameAsync(newName, username);
        }
        
        public string editUsername(string newUsername, string oldUsername) {
            return base.Channel.editUsername(newUsername, oldUsername);
        }
        
        public System.Threading.Tasks.Task<string> editUsernameAsync(string newUsername, string oldUsername) {
            return base.Channel.editUsernameAsync(newUsername, oldUsername);
        }
        
        public string getUsernameById(int id) {
            return base.Channel.getUsernameById(id);
        }
        
        public System.Threading.Tasks.Task<string> getUsernameByIdAsync(int id) {
            return base.Channel.getUsernameByIdAsync(id);
        }
        
        public string editEmail(string newEmail, string username) {
            return base.Channel.editEmail(newEmail, username);
        }
        
        public System.Threading.Tasks.Task<string> editEmailAsync(string newEmail, string username) {
            return base.Channel.editEmailAsync(newEmail, username);
        }
        
        public string editPassword(string newPassword, string oldPassword, string username) {
            return base.Channel.editPassword(newPassword, oldPassword, username);
        }
        
        public System.Threading.Tasks.Task<string> editPasswordAsync(string newPassword, string oldPassword, string username) {
            return base.Channel.editPasswordAsync(newPassword, oldPassword, username);
        }
        
        public string getUserData(string username) {
            return base.Channel.getUserData(username);
        }
        
        public System.Threading.Tasks.Task<string> getUserDataAsync(string username) {
            return base.Channel.getUserDataAsync(username);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppProiect.ServiceReference1.insertImageResponse WindowsFormsAppProiect.ServiceReference1.WebService1Soap.insertImage(WindowsFormsAppProiect.ServiceReference1.insertImageRequest request) {
            return base.Channel.insertImage(request);
        }
        
        public string insertImage(byte[] arr, string username) {
            WindowsFormsAppProiect.ServiceReference1.insertImageRequest inValue = new WindowsFormsAppProiect.ServiceReference1.insertImageRequest();
            inValue.arr = arr;
            inValue.username = username;
            WindowsFormsAppProiect.ServiceReference1.insertImageResponse retVal = ((WindowsFormsAppProiect.ServiceReference1.WebService1Soap)(this)).insertImage(inValue);
            return retVal.insertImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.insertImageResponse> WindowsFormsAppProiect.ServiceReference1.WebService1Soap.insertImageAsync(WindowsFormsAppProiect.ServiceReference1.insertImageRequest request) {
            return base.Channel.insertImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.insertImageResponse> insertImageAsync(byte[] arr, string username) {
            WindowsFormsAppProiect.ServiceReference1.insertImageRequest inValue = new WindowsFormsAppProiect.ServiceReference1.insertImageRequest();
            inValue.arr = arr;
            inValue.username = username;
            return ((WindowsFormsAppProiect.ServiceReference1.WebService1Soap)(this)).insertImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsAppProiect.ServiceReference1.getImageResponse WindowsFormsAppProiect.ServiceReference1.WebService1Soap.getImage(WindowsFormsAppProiect.ServiceReference1.getImageRequest request) {
            return base.Channel.getImage(request);
        }
        
        public byte[] getImage(string username) {
            WindowsFormsAppProiect.ServiceReference1.getImageRequest inValue = new WindowsFormsAppProiect.ServiceReference1.getImageRequest();
            inValue.username = username;
            WindowsFormsAppProiect.ServiceReference1.getImageResponse retVal = ((WindowsFormsAppProiect.ServiceReference1.WebService1Soap)(this)).getImage(inValue);
            return retVal.getImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.getImageResponse> WindowsFormsAppProiect.ServiceReference1.WebService1Soap.getImageAsync(WindowsFormsAppProiect.ServiceReference1.getImageRequest request) {
            return base.Channel.getImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsAppProiect.ServiceReference1.getImageResponse> getImageAsync(string username) {
            WindowsFormsAppProiect.ServiceReference1.getImageRequest inValue = new WindowsFormsAppProiect.ServiceReference1.getImageRequest();
            inValue.username = username;
            return ((WindowsFormsAppProiect.ServiceReference1.WebService1Soap)(this)).getImageAsync(inValue);
        }
        
        public System.Data.DataSet getPostByTitle(string title) {
            return base.Channel.getPostByTitle(title);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPostByTitleAsync(string title) {
            return base.Channel.getPostByTitleAsync(title);
        }
        
        public System.Data.DataSet getComments(string title) {
            return base.Channel.getComments(title);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getCommentsAsync(string title) {
            return base.Channel.getCommentsAsync(title);
        }
        
        public void postComment(string title, int idUser, string content) {
            base.Channel.postComment(title, idUser, content);
        }
        
        public System.Threading.Tasks.Task postCommentAsync(string title, int idUser, string content) {
            return base.Channel.postCommentAsync(title, idUser, content);
        }
        
        public System.Data.DataSet getLinkByTitle(string title) {
            return base.Channel.getLinkByTitle(title);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getLinkByTitleAsync(string title) {
            return base.Channel.getLinkByTitleAsync(title);
        }
        
        public System.Data.DataSet getPostById(int id) {
            return base.Channel.getPostById(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getPostByIdAsync(int id) {
            return base.Channel.getPostByIdAsync(id);
        }
        
        public System.Data.DataSet getTitleByCourse(string course) {
            return base.Channel.getTitleByCourse(course);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getTitleByCourseAsync(string course) {
            return base.Channel.getTitleByCourseAsync(course);
        }
    }
}
